
import { Language, ConsultationRecord, DoctorProfile } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    start: "Start New Consultation",
    subtitle: "Your AI Health Assistant - Get preliminary diagnosis before traveling to hospital",
    upload: "Upload Photo/Video",
    record: "Record Voice",
    analyze: "Analyze Symptoms",
    urgency_high: "⚠️ URGENT - See doctor within 24 hours",
    urgency_low: "✓ Non-urgent - Home care possible",
    call_emergency: "Call Emergency 108",
    symptom_placeholder: "Describe your symptoms...",
    duration: "How long?",
    pain: "Pain Level",
    analyzing: "AI Doctor analyzing your symptoms...",
    report_download: "Download PDF Report",
    share: "Share via WhatsApp",
    home_remedies: "Home Remedies",
    doctor_visit: "When to see a doctor immediately",
    preliminary: "Preliminary Assessment",
    welcome: "Welcome to GramHealth AI. I am here to help you get medical advice.",
    disclaimer_title: "Important Medical Disclaimer",
    disclaimer_text: "This app uses Artificial Intelligence to provide preliminary assessments. It is NOT a doctor. In case of emergency, chest pain, or difficulty breathing, go to a hospital immediately.",
    accept: "I Understand",
    offline_mode: "Offline Mode: Results will be saved locally.",
    success_title: "Analysis Complete!",
    success_subtitle: "Your preliminary report is ready.",
    view_report: "View Report",
    saving: "Saving...",
    saved: "Saved",
    media_instruction: "Photos or videos of detected symptoms",
    photo: "Upload Photo",
    take_photo: "Take Photo",
    capture: "Capture",
    video: "Upload Video",
    describe_symptoms: "Describe Symptoms",
    tap_mic: "Tap mic to speak",
    new_scan: "New Scan",
    visual_evidence: "Visual Evidence",
    hide_overlay: "Hide Overlay",
    show_overlay: "Show Overlay",
    no_image: "No image provided",
    primary_diagnosis: "Primary Diagnosis",
    confidence: "Confidence",
    recommendation: "Recommendation",
    home_care: "Home Care",
    doctor_portal: "Doctor Portal",
    start_video: "Record Video",
    stop_video: "Stop Recording",
    recording_time_limit: "Max 1 min",
    analyze_disabled_hint: "Add photo/video or text to start",
    // Permissions
    perm_title: "Enable App Permissions",
    perm_desc: "To provide the best medical analysis, GramHealth needs access to:",
    perm_mic: "Allow microphone",
    perm_mic_desc: "So you can speak your symptoms instead of typing",
    perm_cam: "Allow camera and media",
    perm_cam_desc: "So you can take or upload photos and videos of the problem",
    perm_allow_all: "Allow all",
    perm_custom: "Continue with custom permissions",
    perm_continue: "Continue",
  },
  hi: {
    start: "नया परामर्श शुरू करें",
    subtitle: "आपका एआई स्वास्थ्य सहायक - अस्पताल जाने से पहले प्रारंभिक निदान प्राप्त करें",
    upload: "फोटो/वीडियो अपलोड करें",
    record: "आवाज़ रिकॉर्ड करें",
    analyze: "लक्षणों का विश्लेषण करें",
    urgency_high: "⚠️ अत्यावश्यक - 24 घंटे के भीतर डॉक्टर से मिलें",
    urgency_low: "✓ सामान्य - घर पर देखभाल संभव",
    call_emergency: "आपातकालीन 108 पर कॉल करें",
    symptom_placeholder: "अपने लक्षणों का वर्णन करें...",
    duration: "कब से?",
    pain: "दर्द का स्तर",
    analyzing: "एआई डॉक्टर आपके लक्षणों की जांच कर रहा है...",
    report_download: "PDF रिपोर्ट डाउनलोड करें",
    share: "व्हाट्सएप पर शेयर करें",
    home_remedies: "घरेलू उपचार",
    doctor_visit: "डॉक्टर को कब दिखाना चाहिए",
    preliminary: "प्रारंभिक मूल्यांकन",
    welcome: "ग्रामहेल्थ एआई में आपका स्वागत है।",
    disclaimer_title: "महत्वपूर्ण चिकित्सा अस्वीकरण",
    disclaimer_text: "यह ऐप केवल प्रारंभिक सलाह देता है। यह डॉक्टर नहीं है। आपात स्थिति में तुरंत अस्पताल जाएं।",
    accept: "मैं समझता हूँ",
    offline_mode: "ऑफ़लाइन मोड: परिणाम स्थानीय रूप से सहेजे जाएंगे।",
    success_title: "विश्लेषण पूर्ण!",
    success_subtitle: "आपकी रिपोर्ट तैयार है।",
    view_report: "रिपोर्ट देखें",
    saving: "सहेज रहा है...",
    saved: "सहेजा गया",
    media_instruction: "लक्षणों की फोटो या वीडियो",
    photo: "फोटो अपलोड",
    take_photo: "फोटो लें",
    capture: "कैप्चर",
    video: "ভিডিও अपलोड",
    describe_symptoms: "लक्षण बताएं",
    tap_mic: "बोलने के लिए टैप करें",
    new_scan: "नई स्कैन",
    visual_evidence: "दृश्य प्रमाण",
    hide_overlay: "ओवरले छिपाएं",
    show_overlay: "ओवरले दिखाएं",
    no_image: "कोई छवि नहीं",
    primary_diagnosis: "प्रारंभिक निदान",
    confidence: "विश्वास",
    recommendation: "सलाह",
    home_care: "घरेलू देखभाल",
    doctor_portal: "डॉक्टर पोर्टल",
    start_video: "वीडियो रिकॉर्ड",
    stop_video: "रिकॉर्डिंग रोकें",
    recording_time_limit: "अधिकतम 1 मिनट",
    analyze_disabled_hint: "शुरू करने के लिए फोटो/वीडियो या टेक्स्ट जोड़ें",
    // Permissions
    perm_title: "ऐप अनुमतियां सक्षम करें",
    perm_desc: "सर्वोत्तम विश्लेषण के लिए:",
    perm_mic: "माइक्रोफोन की अनुमति दें",
    perm_mic_desc: "ताकि आप टाइप करने के बजाय बोल सकें",
    perm_cam: "कैमरा और मीडिया की अनुमति दें",
    perm_cam_desc: "ताकि आप समस्या की फोटो और वीडियो ले सकें",
    perm_allow_all: "सभी की अनुमति दें",
    perm_custom: "कस्टम अनुमतियों के साथ जारी रखें",
    perm_continue: "जारी रखें",
  },
  ta: {
    start: "புதிய ஆலோசனையைத் தொடங்கவும்",
    subtitle: "உங்கள் AI சுகாதார உதவியாளர் - மருத்துவமனைக்குச் செல்வதற்கு முன் முதற்கட்ட நோயறிதலைப் பெறுங்கள்",
    upload: "புகைப்படம்/வீடியோ பதிவேற்றவும்",
    record: "குரல் பதிவு",
    analyze: "அறிகுறிகளை ஆய்வு செய்",
    urgency_high: "⚠️ அவசரம் - 24 மணி நேரத்திற்குள் மருத்துவரைப் பார்க்கவும்",
    urgency_low: "✓ அவசரமில்லை - வீட்டு பராமரிப்பு சாத்தியம்",
    call_emergency: "அவசர எண் 108 ஐ அழைக்கவும்",
    symptom_placeholder: "உங்கள் அறிகுறிகளை விவரிக்கவும்...",
    duration: "எவ்வளவு காலம்?",
    pain: "வலி அளவு",
    analyzing: "AI மருத்துவர் உங்கள் அறிகுறிகளை ஆய்வு செய்கிறார்...",
    report_download: "PDF அறிக்கையைப் பதிவிறக்கவும்",
    share: "வாட்ஸ்அப்பில் பகிரவும்",
    home_remedies: "வீட்டு வைத்தியம்",
    doctor_visit: "உடனடியாக மருத்துவரை எப்போது பார்க்க வேண்டும்",
    preliminary: "முதற்கட்ட மதிப்பீடு",
    welcome: "GramHealth AI க்கு வரவேற்கிறோம்.",
    disclaimer_title: "முக்கிய மருத்துவ மறுப்பு",
    disclaimer_text: "இந்த பயன்பாடு முதற்கட்ட மதிப்பீட்டை மட்டுமே வழங்குகிறது. இது மருத்துவர் அல்ல.",
    accept: "எனக்கு புரிகிறது",
    offline_mode: "ஆஃப்லைன் பயன்முறை",
    success_title: "ஆய்வு முடிந்தது!",
    success_subtitle: "உங்கள் அறிக்கை தயாராக உள்ளது.",
    view_report: "அறிக்கையைப் பார்க்கவும்",
    saving: "சேமிக்கிறது...",
    saved: "சேமிக்கப்பட்டது",
    media_instruction: "அறிகுறிகளின் புகைப்படம் அல்லது வீடியோ",
    photo: "புகைப்படம்",
    take_photo: "புகைப்படம் எடு",
    capture: "பிடிப்பு",
    video: "வீடியோ",
    describe_symptoms: "அறிகுறிகளை விவரிக்கவும்",
    tap_mic: "பேச தட்டவும்",
    new_scan: "புதிய ஸ்கேன்",
    visual_evidence: "காட்சி ஆதாரம்",
    hide_overlay: "மேலடுக்கை மறை",
    show_overlay: "மேலடுக்கைக் காட்டு",
    no_image: "படம் இல்லை",
    primary_diagnosis: "முதன்மை நோயறிதல்",
    confidence: "நம்பிக்கை",
    recommendation: "பரிந்துரை",
    home_care: "வீட்டு பராமரிப்பு",
    doctor_portal: "மருத்துவர் போர்டல்",
    start_video: "வீடியோ பதிவு",
    stop_video: "பதிவை நிறுத்து",
    recording_time_limit: "அதிகபட்சம் 1 நிமிடம்",
    analyze_disabled_hint: "தொடங்க புகைப்படம்/வீடியோ அல்லது உரையைச் சேர்க்கவும்",
    // Permissions
    perm_title: "அனுமதிகளை இயக்கவும்",
    perm_desc: "சிறந்த சேவைக்கு:",
    perm_mic: "மைக்ரோஃபோனை அனுமதி",
    perm_mic_desc: "பேசி பதிவு செய்ய",
    perm_cam: "கேமராவை அனுமதி",
    perm_cam_desc: "புகைப்படம் எடுக்க",
    perm_allow_all: "அனைத்தையும் அனுமதி",
    perm_custom: "விருப்பத் தேர்வு",
    perm_continue: "தொடரவும்",
  },
  bn: {
    start: "নতুন পরামর্শ শুরু করুন",
    subtitle: "আপনার এআই স্বাস্থ্য সহকারী - হাসপাতালে যাওয়ার আগে প্রাথমিক রোগ নির্ণয় করুন",
    upload: "ফটো/ভিডিও আপলোড করুন",
    record: "ভয়েস রেকর্ড করুন",
    analyze: "লক্ষণ বিশ্লেষণ করুন",
    urgency_high: "⚠️ জরুরি - 24 ঘন্টার মধ্যে ডাক্তার দেখান",
    urgency_low: "✓ জরুরি নয় - বাড়িতে যত্ন সম্ভব",
    call_emergency: "জরুরি 108 কল করুন",
    symptom_placeholder: "আপনার লক্ষণ বর্ণনা করুন...",
    duration: "কত দিন?",
    pain: "ব্যথার মাত্রা",
    analyzing: "এআই ডাক্তার আপনার লক্ষণ বিশ্লেষণ করছে...",
    report_download: "PDF রিপোর্ট ডাউনলোড করুন",
    share: "হোয়াটসঅ্যাপে শেয়ার করুন",
    home_remedies: "ঘরোয়া প্রতিকার",
    doctor_visit: "কখন অবিলম্বে ডাক্তার দেখাবেন",
    preliminary: "প্রাথমিক মূল্যায়ন",
    welcome: "GramHealth AI তে স্বাগতম।",
    disclaimer_title: "গুরুত্বপূর্ণ দাবিত্যাগ",
    disclaimer_text: "এটি একটি ডাক্তার নয়। জরুরি অবস্থায় হাসপাতালে যান।",
    accept: "আমি বুঝেছি",
    offline_mode: "অফলাইন মোড",
    success_title: "বিশ্লেষণ সম্পূর্ণ!",
    success_subtitle: "আপনার রিপোর্ট প্রস্তুত।",
    view_report: "রিপোর্ট দেখুন",
    saving: "সংরক্ষণ করা হচ্ছে...",
    saved: "সংরক্ষিত",
    media_instruction: "লক্ষণগুলির ছবি বা ভিডিও",
    photo: "ছবি",
    take_photo: "ছবি তোল",
    capture: "ক্যাপচার",
    video: "ভিডিও",
    describe_symptoms: "লক্ষণ বর্ণনা করুন",
    tap_mic: "কথা বলতে আলতো চাপুন",
    new_scan: "নতুন স্ক্যান",
    visual_evidence: "ভিজ্যুয়াল প্রমাণ",
    hide_overlay: "ওভারলে লুকান",
    show_overlay: "ওভারলে দেখান",
    no_image: "কোন ছবি নেই",
    primary_diagnosis: "প্রাথমিক রোগ নির্ণয়",
    confidence: "আত্মবিশ্বাস",
    recommendation: "সুপারিশ",
    home_care: "গাহস্থ্য যত্ন",
    doctor_portal: "ডাক্তার পোর্টাল",
    start_video: "ভিডিও রেকর্ড",
    stop_video: "রেকর্ডিং বন্ধ করুন",
    recording_time_limit: "সর্বোচ্চ ১ মিনিট",
    analyze_disabled_hint: "শুরু করতে ছবি/ভিডিও বা টেক্সট যোগ করুন",
     // Permissions
    perm_title: "অনুমতি সক্রিয় করুন",
    perm_desc: "সেরা পরিষেবার জন্য প্রয়োজন:",
    perm_mic: "মাইক্রোফোন অনুমতি দিন",
    perm_mic_desc: "লক্ষণগুলি বলতে",
    perm_cam: "ক্যামেরা অনুমতি দিন",
    perm_cam_desc: "ছবি/ভিডিও তুলতে",
    perm_allow_all: "সব অনুমতি দিন",
    perm_custom: "কাস্টম অনুমতি",
    perm_continue: "চালিয়ে যান",
  },
  mr: {
    start: "नवीन सल्लामसलत सुरू करा",
    subtitle: "तुमचा एआय हेल्थ असिस्टंट - हॉस्पिटलला जाण्यापूर्वी प्राथमिक निदान मिळवा",
    upload: "फोटो/व्हिडिओ अपलोड करा",
    record: "आवाज रेकॉर्ड करा",
    analyze: "लक्षणांचे विश्लेषण करा",
    urgency_high: "⚠️ तातडीचे - 24 तासांच्या आत डॉक्टरांना भेटा",
    urgency_low: "✓ तातडीचे नाही - घरगुती काळजी शक्य",
    call_emergency: "आपत्कालीन 108 वर कॉल करा",
    symptom_placeholder: "तुमच्या लक्षणांचे वर्णन करा...",
    duration: "किती वेळ?",
    pain: "वेदना पातळी",
    analyzing: "एआई डॉक्टर तुमच्या लक्षणांचे विश्लेषण करत आहे...",
    report_download: "PDF अहवाल डाउनलोड करा",
    share: "व्हॉट्सॲपवर शेअर करा",
    home_remedies: "घरगुती उपाय",
    doctor_visit: "डॉक्टरांना त्वरित कधी भेटावे",
    preliminary: "प्राथमिक मूल्यांकन",
    welcome: "GramHealth AI मध्ये आपले स्वागत आहे.",
    disclaimer_title: "महत्त्वाचे वैद्यकीय अस्वीकरण",
    disclaimer_text: "हे ॲप डॉक्टर नाही. आपत्कालीन परिस्थितीत हॉस्पिटलला जा.",
    accept: "मला समजले",
    offline_mode: "ऑफलाइन मोड",
    success_title: "विश्लेषण पूर्ण!",
    success_subtitle: "तुमचा अहवाल तयार आहे.",
    view_report: "अहवाल पहा",
    saving: "जतन करत आहे...",
    saved: "जतन केले",
    media_instruction: "लक्षणांचे फोटो किंवा व्हिडिओ",
    photo: "फोटो",
    take_photo: "फोटो घ्या",
    capture: "फोटो काढा",
    video: "व्हिडिओ",
    describe_symptoms: "लक्षणे सांगा",
    tap_mic: "बोलण्यासाठी टॅप करा",
    new_scan: "नवीन स्कॅन",
    visual_evidence: "दृश्य पुरावा",
    hide_overlay: "ओव्हरले लपवा",
    show_overlay: "ओव्हरले दाखवा",
    no_image: "कोणतीही प्रतिमा नाही",
    primary_diagnosis: "प्राथमिक निदान",
    confidence: "आत्मविश्वास",
    recommendation: "शिफारस",
    home_care: "घरगुती काळजी",
    doctor_portal: "डॉक्टर पोर्टल",
    start_video: "व्हिडिओ रेकॉर्ड",
    stop_video: "रेकॉर्डिंग थांबवा",
    recording_time_limit: "जास्तीत जास्त 1 मि",
    analyze_disabled_hint: "सुरू करण्यासाठी फोटो/व्हिडिओ किंवा मजकूर जोडा",
     // Permissions
    perm_title: "परवानग्या सक्षम करें",
    perm_desc: "सर्वोत्तम सेवेसाठी:",
    perm_mic: "मायक्रोफोनला अनुमती द्या",
    perm_mic_desc: "लक्षणे सांगण्यासाठी",
    perm_cam: "कॅमेराला अनुमती द्या",
    perm_cam_desc: "समस्यांचे फोटो/व्हिडिओ काढण्यासाठी",
    perm_allow_all: "सर्व अनुमती द्या",
    perm_custom: "सानुकूल परवानग्या",
    perm_continue: "पुढे सुरू ठेवा",
  },
  kn: {
    start: "ಹೊಸ ಸಮಾಲೋಚನೆ ಪ್ರಾರಂಭಿಸಿ",
    subtitle: "ನಿಮ್ಮ AI ಆರೋಗ್ಯ ಸಹಾಯಕ - ಆಸ್ಪತ್ರೆಗೆ ಹೋಗುವ ಮೊದಲು ಪ್ರಾಥಮಿಕ ರೋಗನಿರ್ಣಯವನ್ನು ಪಡೆಯಿರಿ",
    upload: "ಫೋಟೋ/ವೀಡಿಯೊ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    record: "ಧ್ವನಿ ರೆಕಾರ್ಡ್ ಮಾಡಿ",
    analyze: "ರೋಗಲಕ್ಷಣಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ",
    urgency_high: "⚠️ ತುರ್ತು - 24 ಗಂಟೆಗಳ ಒಳಗೆ ವೈದ್ಯರನ್ನು ಭೇಟಿ ಮಾಡಿ",
    urgency_low: "✓ ತುರ್ತು ಅಲ್ಲ - ಮನೆಯಲ್ಲೇ ಆರೈಕೆ ಸಾಧ್ಯ",
    call_emergency: "ತುರ್ತು 108 ಗೆ ಕರೆ ಮಾಡಿ",
    symptom_placeholder: "ನಿಮ್ಮ ರೋಗಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ...",
    duration: "ಎಷ್ಟು ಸಮಯ?",
    pain: "ನೋವಿನ ಮಟ್ಟ",
    analyzing: "AI ವೈದ್ಯರು ನಿಮ್ಮ ರೋಗಲಕ್ಷಣಗಳನ್ನು ಪರಿಶೀಲಿಸುತ್ತಿದ್ದಾರೆ...",
    report_download: "PDF ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    share: "WhatsApp ಮೂಲಕ ಹಂಚಿಕೊಳ್ಳಿ",
    home_remedies: "ಮನೆಮದ್ದುಗಳು",
    doctor_visit: "ವೈದ್ಯರನ್ನು ಯಾವಾಗ ನೋಡಬೇಕು",
    preliminary: "ಪ್ರಾಥಮಿಕ ಮೌಲ್ಯಮಾಪನ",
    welcome: "GramHealth AI ಗೆ ಸುಸ್ವಾಗತ.",
    disclaimer_title: "ಪ್ರಮುಖ ವೈದ್ಯಕೀಯ ಹಕ್ಕು ನಿರಾಕರಣೆ",
    disclaimer_text: "ಇದು ವೈದ್ಯರಲ್ಲ. ತುರ್ತು ಸಂದರ್ಭದಲ್ಲಿ ಆಸ್ಪತ್ರೆಗೆ ಹೋಗಿ.",
    accept: "ನನಗೆ ಅರ್ಥವಾಯಿತು",
    offline_mode: "ಆಫ್‌ಲೈನ್ ಮೋಡ್",
    success_title: "ವಿಶ್ಲೇಷಣೆ ಪೂರ್ಣಗೊಂಡಿದೆ!",
    success_subtitle: "ನಿಮ್ಮ ವರದಿ ಸಿದ್ಧವಾಗಿದೆ.",
    view_report: "ವರದಿ ವೀಕ್ಷಿಸಿ",
    saving: "ಉಳಿಸಲಾಗುತ್ತಿದೆ...",
    saved: "ಉಳಿಸಲಾಗಿದೆ",
    media_instruction: "ರೋಗಲಕ್ಷಣಗಳ ಫೋಟೋ ಅಥವಾ ವೀಡಿಯೊ",
    photo: "ಫೋಟೋ",
    take_photo: "ಫೋಟೋ ತೆಗೆದುಕೊಳ್ಳಿ",
    capture: "ಸೆರೆಹಿಡಿಯಿರಿ",
    video: "ವೀಡಿಯೊ",
    describe_symptoms: "ರೋಗಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ",
    tap_mic: "ಮಾತನಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
    new_scan: "ಹೊಸ ಸ್ಕ್ಯಾನ್",
    visual_evidence: "ದೃಶ್ಯ ಪುರಾವೆ",
    hide_overlay: "ಓವರ್‌ಲೇ ಮರೆಮಾಡಿ",
    show_overlay: "ಓವರ್‌ಲೇ ತೋರಿಸಿ",
    no_image: "ಯಾವುದೇ ಚಿತ್ರವಿಲ್ಲ",
    primary_diagnosis: "ಪ್ರಾಥಮಿಕ ರೋಗನಿರ್ಣಯ",
    confidence: "ನಂಬಿಕೆ",
    recommendation: "ಶಿಫಾರಸು",
    home_care: "ಮನೆಯ ಆರೈಕೆ",
    doctor_portal: "ವೈದ್ಯರ ಪೋರ್ಟಲ್",
    start_video: "ವೀಡಿಯೊ ರೆಕಾರ್ಡ್",
    stop_video: "ರೆಕಾರ್ಡಿಂಗ್ ನಿಲ್ಲಿಸಿ",
    recording_time_limit: "ಗರಿಷ್ಠ 1 ನಿಮಿಷ",
    analyze_disabled_hint: "ಪ್ರಾರಂಭಿಸಲು ಫೋಟೋ/ವೀಡಿಯೊ ಅಥವಾ ಪಠ್ಯವನ್ನು ಸೇರಿಸಿ",
     // Permissions
    perm_title: "ಅನುಮತಿಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ",
    perm_desc: "ಉತ್ತಮ ಸೇವೆಗಾಗಿ:",
    perm_mic: "ಮೈಕ್ರೊಫೋನ್ ಅನುಮತಿಸಿ",
    perm_mic_desc: "ರೋಗಲಕ್ಷಣಗಳನ್ನು ಹೇಳಲು",
    perm_cam: "ಕ್ಯಾಮೆರಾ ಅನುಮತಿಸಿ",
    perm_cam_desc: "ಫೋಟೋ ತೆಗೆಯಲು",
    perm_allow_all: "ಎಲ್ಲವನ್ನೂ ಅನುಮತಿಸಿ",
    perm_custom: "ಕಸ್ಟಮ್ ಅನುಮತಿಗಳು",
    perm_continue: "ಮುಂದುವರಿಸಿ",
  },
};

export const SYMPTOM_TAGS = ["Fever", "Nausea", "Dizziness", "Fatigue", "Swelling", "Rash", "Cough", "Bleeding"];
export const DURATION_OPTIONS = ["1 day", "2-7 days", "1-2 weeks", "> 1 month"];

export const GUIDED_VIDEO_PROMPTS = [
    { label: "Walk normally (10s)", hint: "Place phone on floor/table and walk away then back" },
    { label: "Show Range of Motion", hint: "Slowly move the affected joint as much as possible" },
    { label: "Describe & Point", hint: "Point to pain area while speaking about symptoms" }
];

export const DEMO_CONSULTATIONS: ConsultationRecord[] = [
  {
    id: 'demo1',
    date: Date.now() - 86400000 * 2,
    shareCode: "GH-2025-FUN",
    patientData: { symptoms: "Red rash on forearm, itchy", duration: "2-7 days", painLevel: 3, otherSymptoms: ["Rash"], mediaFiles: [] },
    analysisResult: {
      boundingBoxes: [{ymin:0, xmin:0, ymax:0, xmax:0, label: "Rash", confidence: 95, severity: 'moderate'}],
      diagnoses: [{
        name: "Fungal Infection (Tinea Corporis)", localName: "Dadru (Fungal)", explanation: "Common fungal skin infection causing red, itchy ring.", 
        recommendation: "Keep dry, apply antifungal cream.", likelihood: 92, urgency: 'NON-URGENT', pronunciation: "Tin-ee-uh Cor-por-is"
      }],
      overallExplanation: "Likely a fungal infection (Ringworm). Keep area dry.",
      recommendedTests: ["Skin scraping"],
      visualDiagramQuery: "Fungal infection skin layers"
    }
  },
  {
    id: 'demo2',
    date: Date.now() - 86400000 * 5,
    shareCode: "GH-2025-CEL",
    patientData: { symptoms: "Swollen right leg, warm to touch", duration: "2-7 days", painLevel: 8, otherSymptoms: ["Swelling", "Fever"], mediaFiles: [] },
    analysisResult: {
      boundingBoxes: [{ymin:0, xmin:0, ymax:0, xmax:0, label: "Swelling", confidence: 98, severity: 'high'}],
      diagnoses: [{
        name: "Cellulitis", localName: "Bacterial Infection", explanation: "Bacterial skin infection causing redness, heat, and swelling.", 
        recommendation: "See doctor immediately for antibiotics.", likelihood: 89, urgency: 'URGENT', pronunciation: "Sell-u-light-is"
      }],
      overallExplanation: "Possible serious infection (Cellulitis). Needs doctor visit immediately.",
      recommendedTests: ["Blood count"],
      doctorWarning: "Spread of redness, high fever"
    }
  }
];

export const MOCK_DOCTORS: DoctorProfile[] = [
    {
        id: 'd1', name: "Dr. Rajesh Gupta", specialty: "Dermatologist", hospital: "City General Hospital",
        rating: 4.8, fee: 500, isOnline: true, imageUrl: "https://img.icons8.com/color/96/doctor-male.png"
    },
    {
        id: 'd2', name: "Dr. Anita Desai", specialty: "General Physician", hospital: "Rural Health Clinic",
        rating: 4.5, fee: 300, isOnline: false, imageUrl: "https://img.icons8.com/color/96/doctor-female.png"
    },
     {
        id: 'd3', name: "Dr. Vikram Singh", specialty: "Orthopedic", hospital: "Bone & Joint Center",
        rating: 4.9, fee: 800, isOnline: true, imageUrl: "https://img.icons8.com/color/96/doctor-male--v2.png"
    }
];

export const MOCK_COMMUNITY_STATS = {
    region: "Karnataka Rural District",
    activeAlerts: [
        { title: "Viral Fever Outbreak", severity: 'moderate' },
        { title: "Dengue Warning", severity: 'high' }
    ],
    commonSymptoms: [
        { name: "Fever", percentage: 45 },
        { name: "Cough", percentage: 30 },
        { name: "Skin Rash", percentage: 15 }
    ],
    seasonalTips: [
        "Boil water before drinking due to recent rains.",
        "Use mosquito nets to prevent Dengue.",
        "Keep skin dry to avoid fungal infections."
    ]
};
