import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useApp } from '../App';
import { AnalysisResult, PatientData, ConsultationRecord } from '../types';
import { Share2, Download, ArrowLeft, Key, Copy } from 'lucide-react';

// Declare html2pdf for TypeScript
declare const html2pdf: any;

const Report: React.FC = () => {
  const { t, language, darkMode } = useApp();
  const navigate = useNavigate();
  const [data, setData] = useState<PatientData | null>(null);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [shareCode, setShareCode] = useState<string>('');

  useEffect(() => {
    const fullRecordStr = sessionStorage.getItem('currentRecord');
    if (fullRecordStr) {
        const fullRecord: ConsultationRecord = JSON.parse(fullRecordStr);
        setData(fullRecord.patientData);
        setResult(fullRecord.analysisResult);
        if (fullRecord.shareCode) {
            setShareCode(fullRecord.shareCode);
        } else {
            setShareCode(`GH-${new Date().getFullYear()}-${Math.floor(Math.random()*10000)}`);
        }
    } else {
        const pData = sessionStorage.getItem('patientData');
        const aResult = sessionStorage.getItem('analysisResult');
        if (pData) setData(JSON.parse(pData));
        if (aResult) setResult(JSON.parse(aResult));
        setShareCode(`GH-${new Date().getFullYear()}-${Math.floor(Math.random()*10000)}`);
    }
  }, []);

  if (!data || !result) {
    return <div className={`p-8 text-center ${darkMode ? 'text-white' : 'text-gray-800'}`}>Loading Report...</div>;
  }

  const handleDownloadPDF = () => {
      const element = document.getElementById('medical-report');
      if (element && typeof html2pdf !== 'undefined') {
          const opt = {
              margin: 10,
              filename: `GramHealth-Report-${shareCode}.pdf`,
              image: { type: 'jpeg', quality: 0.98 },
              html2canvas: { scale: 2 },
              jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
          };
          html2pdf().set(opt).from(element).save();
      } else {
          window.print();
      }
  };

  const handleShare = () => {
    const text = `GramHealth Report for Patient:\nDiagnosis: ${result.diagnoses[0].name}\nUrgency: ${result.diagnoses[0].urgency}\nDoctor Access Code: ${shareCode}`;
    const url = `https://wa.me/?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank');
  };

  return (
    <div className={`p-4 pb-24 min-h-screen ${darkMode ? 'bg-gray-900' : 'bg-white'}`}>
      <div className="flex justify-between items-center mb-6 print:hidden">
          <button onClick={() => navigate(-1)} className={`p-2 rounded-full ${darkMode ? 'bg-gray-800 text-white' : 'bg-gray-100 text-gray-800'}`}>
            <ArrowLeft />
          </button>
          <div className="flex gap-2">
            <button onClick={handleShare} className="flex items-center gap-2 px-4 py-2 bg-green-500 text-white rounded-lg font-bold">
                <Share2 size={20}/> Share
            </button>
            <button onClick={handleDownloadPDF} className="flex items-center gap-2 px-4 py-2 bg-medical-blue text-white rounded-lg font-bold">
                <Download size={20}/> PDF
            </button>
          </div>
      </div>

      <div id="medical-report" className={`max-w-3xl mx-auto border p-8 print:border-none print:p-0 ${darkMode ? 'bg-gray-800 border-gray-700 text-gray-100' : 'bg-white border-gray-200 text-gray-900'}`}>
          {/* Header */}
          <div className="border-b-4 border-medical-blue pb-4 mb-6 flex justify-between items-end">
              <div>
                  <h1 className={`text-3xl font-bold ${darkMode ? 'text-white' : 'text-gray-900'}`}>Medical Consultation Report</h1>
                  <p className={`${darkMode ? 'text-gray-400' : 'text-gray-500'} mt-1`}>Generated by GramHealth AI</p>
                  <p className={`text-sm ${darkMode ? 'text-gray-500' : 'text-gray-400'}`}>Date: {new Date().toLocaleDateString()}</p>
              </div>
              <div className="text-right">
                  <div className={`px-4 py-1 rounded text-white font-bold inline-block ${result.diagnoses[0].urgency === 'URGENT' ? 'bg-red-600' : 'bg-green-600'}`}>
                      {result.diagnoses[0].urgency}
                  </div>
              </div>
          </div>

          {/* Doctor Access Section */}
          <div className="mb-8 p-4 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-xl print:hidden">
              <h3 className="font-bold text-medical-blue flex items-center gap-2 mb-2">
                  <Key size={18} /> Doctor Collaboration
              </h3>
              <p className="text-sm opacity-80 mb-2">Share this code with your doctor to allow them to access this full report and add notes.</p>
              <div className="flex items-center gap-2">
                  <code className="text-lg font-mono font-bold bg-white dark:bg-gray-800 px-3 py-1 rounded border dark:border-gray-600">{shareCode}</code>
                  <button className="text-sm font-bold text-blue-600" onClick={() => navigator.clipboard.writeText(shareCode)}><Copy size={16}/></button>
              </div>
          </div>

          {/* Patient Complaint */}
          <section className="mb-8">
              <h2 className="text-xl font-bold text-medical-blue mb-3 border-b pb-1">Patient Complaint</h2>
              <div className={`grid grid-cols-2 gap-4 ${darkMode ? 'text-gray-200' : 'text-gray-800'}`}>
                  <div>
                      <span className="font-semibold">Primary Symptom:</span>
                      <p className={`p-2 rounded ${darkMode ? 'bg-gray-700' : 'bg-gray-50'}`}>{data.symptoms}</p>
                  </div>
                   <div>
                      <span className="font-semibold">Duration:</span>
                      <p className={`p-2 rounded ${darkMode ? 'bg-gray-700' : 'bg-gray-50'}`}>{data.duration}</p>
                  </div>
                   <div>
                      <span className="font-semibold">Pain Level:</span>
                      <p className={`p-2 rounded ${darkMode ? 'bg-gray-700' : 'bg-gray-50'}`}>{data.painLevel}/10</p>
                  </div>
                   <div>
                      <span className="font-semibold">Tags:</span>
                      <p className={`p-2 rounded ${darkMode ? 'bg-gray-700' : 'bg-gray-50'}`}>{data.otherSymptoms.join(', ') || 'None'}</p>
                  </div>
              </div>
          </section>

          {/* AI Assessment */}
          <section className="mb-8">
              <h2 className="text-xl font-bold text-medical-blue mb-3 border-b pb-1">Clinical Assessment</h2>
              <table className="w-full text-left border-collapse">
                  <thead>
                      <tr className={`${darkMode ? 'bg-gray-700' : 'bg-gray-100'}`}>
                          <th className={`p-2 border ${darkMode ? 'border-gray-600' : 'border-gray-200'}`}>Diagnosis</th>
                          <th className={`p-2 border ${darkMode ? 'border-gray-600' : 'border-gray-200'}`}>Confidence</th>
                          <th className={`p-2 border ${darkMode ? 'border-gray-600' : 'border-gray-200'}`}>Recommendation</th>
                      </tr>
                  </thead>
                  <tbody>
                      {result.diagnoses.map((diag, i) => (
                          <tr key={i} className={`border-b ${darkMode ? 'border-gray-700' : 'border-gray-200'}`}>
                              <td className={`p-2 border ${darkMode ? 'border-gray-600' : 'border-gray-200'}`}>
                                  <div className="font-bold">{diag.name}</div>
                                  <div className={`text-sm ${darkMode ? 'text-gray-400' : 'text-gray-500'}`}>({diag.localName})</div>
                              </td>
                              <td className={`p-2 border text-center ${darkMode ? 'border-gray-600' : 'border-gray-200'}`}>{diag.likelihood}%</td>
                              <td className={`p-2 border text-sm ${darkMode ? 'border-gray-600' : 'border-gray-200'}`}>{diag.recommendation}</td>
                          </tr>
                      ))}
                  </tbody>
              </table>
          </section>

          {/* Visual Findings */}
          <section className="mb-8">
               <h2 className="text-xl font-bold text-medical-blue mb-3 border-b pb-1">Visual Analysis</h2>
               <div className={`p-4 rounded border ${darkMode ? 'bg-gray-700 border-gray-600' : 'bg-gray-50 border-gray-200'}`}>
                   <ul className="list-disc pl-5">
                       {result.boundingBoxes.map((box, i) => (
                           <li key={i} className="mb-1">
                               <span className="font-bold text-red-600">{box.label}</span> (Confidence: {box.confidence}%)
                           </li>
                       ))}
                   </ul>
               </div>
          </section>

           {/* Disclaimer */}
           <div className={`mt-12 pt-4 border-t text-xs text-center ${darkMode ? 'text-gray-500 border-gray-700' : 'text-gray-500 border-gray-200'}`}>
               <p className="font-bold">DISCLAIMER: This is an AI-generated preliminary report.</p>
               <p>This report does not replace professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider.</p>
           </div>
      </div>
    </div>
  );
};

export default Report;